META_TIERS = {
    "Damien": "S",
    "Najia": "S",
    "Colette": "S",
    "Crow": "S",
    "Leon": "S",
    "Mortis": "S",
    "Pierce": "S",
    "Edgar": "S",
    "Chester": "S",
    "Otis": "S",

    "Lumi": "A",
    "Kaze": "A",
    "Kenji": "A",
    "Angelo": "A",
    "Amber": "A",
    "Byron": "A",
    "Rico": "A",
    "Meeple": "A",
    "Emz": "A",
    "Bibi": "A",
    "Colt": "A",
    "Lola": "A",
    "Shade": "A",
    "Clancy": "A",
    "Penny": "A",
    "Nita": "A",
    "Bo": "A",
    "Charlie": "A",
    "Gavs": "A",
    "Mina": "A",
    "Brock": "A",
    "Sirius": "A",
    "Bull": "A"
}